"""initial messages

Revision ID: 656594fb5c2d
Revises: 
Create Date: 2023-07-15 22:57:46.772323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '656594fb5c2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emoji',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emoji')
    # ### end Alembic commands ###
